### ISSUE TITLE
Installation failed for new conda env with python 3.11 on win 11

### ISSUE THREAD

**Issue by luffy-yu** [luffy-yu/conda_env_export#9]
Collecting conda-env-export
  Using cached conda_env_export-0.5.0-py2.py3-none-any.whl.metadata (6.7 kB)
Collecting conda==4.3.16 (from conda-env-export)
  Using cached conda-4.3.16.tar.gz (299 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]

      WARNING: Your current install method for conda only supports conda
      as a python library.  You are not installing a conda executable command
      or activate/deactivate commands.  If your intention is to install conda
      as a standalone application, currently supported install methods include
      the Anaconda installer and the miniconda installer.  If you'd still like
      for setup.py to create entry points for you, use `utils/setup-testing.py`.

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\yuliu\AppData\Local\Temp\pip-install-kowiebl5\conda_7743ed4164444e73a2a02a50d8b5bfe4\setup.py", line 35, in <module>
          import conda._vendor.auxlib.packaging  # NOQA
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\yuliu\AppData\Local\Temp\pip-install-kowiebl5\conda_7743ed4164444e73a2a02a50d8b5bfe4\conda\__init__.py", line 13, in <module>
          from .common.compat import iteritems, text_type
        File "C:\Users\yuliu\AppData\Local\Temp\pip-install-kowiebl5\conda_7743ed4164444e73a2a02a50d8b5bfe4\conda\common\compat.py", line 77, in <module>
          from collections import Iterable
      ImportError: cannot import name 'Iterable' from 'collections' (D:\ProgramData\Anaconda3\envs\cee-debug1\Lib\collections\__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by luffy-yu** [comment]
Solved in v0.6.1 by auto-installing `conda` at the 1st run.
